# Generated by Django 4.0.2 on 2022-03-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sample', '0002_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='slug',
        ),
    ]
